### ISSUE TITLE
可以不使用独显，只用核显吗？

### ISSUE THREAD

**Issue by chujiezheng** [nukewarrior/OpenCore-ASUS-TUF--B365M-PLUS-GAMING-i7-9700#1]

**Comment by nukewarrior** [comment]
可以，你需要删除config里关于独显的设置

**Comment by chujiezheng** [comment]
是修改config.plist里面的参数吗？您可以介绍下具体怎么改吗？

**Comment by nukewarrior** [comment]
> 是修改config.plist里面的参数吗？您可以介绍下具体怎么改吗？

这个我建议你看一下教程[https://dortania.github.io/OpenCore-Desktop-Guide/](url)
